# Generated by Django 3.0.1 on 2019-12-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Commute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('in_traffic', models.IntegerField(null=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('mode', models.CharField(choices=[('transit', 'Public Transportation'), ('driving', 'Driving')], db_index=True, max_length=8)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_maps.Origins')),
            ],
        ),
    ]
