"""
These are the locations used to track commute times to/from Boston.
They are called in 'recurring.py' at the project root.
"""

origins = [
'Milton, Massachusetts',
'Canton, Massachusetts',
'Randolph, Massachusetts',
'Braintree, Massachusetts',
'Quincy, Massachusetts',
'Weymouth, Massachusetts',
'Hingham, Massachusetts',
'Hull , Massachusetts',
'Cohasset, Massachusetts',
'Stoughton, Massachusetts',
'Sharon, Massachusetts',
'Walpole, Massachusetts',
'Westwood, Massachusetts',
'Dedham, Massachusetts',
'Needham, Massachusetts',
'Dover, Massachusetts',
'Natick, Massachusetts',
'Wellesley, Massachusetts',
'Newton, Massachusetts',
'Brookline, Massachusetts',
'Wayland, Massachusetts',
'Framingham, Massachusetts',
'Sherborn, Massachusetts',
'Ashland, Massachusetts',
'Framingham, Massachusetts',
'Sudbury, Massachusetts',
'Weston, Massachusetts',
'Waltham, Massachusetts',
'Cambridge, Massachusetts',
'Watertown, Massachusetts',
'Arlington, Massachusetts',
'Medford, Massachusetts',
'Somerville, Massachusetts',
'Malden, Massachusetts',
'Chelsea, Massachusetts',
'Lincoln, Massachusetts',
'Lexington, Massachusetts',
'Bedford, Massachusetts',
'Woburn, Massachusetts',
'Concord, Massachusetts',
'Acton, Massachusetts',
'Burlington, Massachusetts',
'Everett, Massachusetts',
'Revere, Massachusetts',
'Saugus, Massachusetts',
'Lynn, Massachusetts',
'Melrose, Massachusetts',
'Arlington, Massachusetts',
'Winchester, Massachusetts',
'Salem, Massachusetts',
'Peabody, Massachusetts',
'Danvers , Massachusetts',
'Beverly, Massachusetts',
'Stoneham, Massachusetts',
'Medfield, Massachusetts',
'Sherborn, Massachusetts',
'Foxborough, Massachusetts',
'Brockton, Massachusetts',
'Rockland, Massachusetts',
'Marshfield, Massachusetts',
'Norwell, Massachusetts',
'Scituate, Massachusetts',
'Winthrop, Massachusetts',
'Worcester, Massachusetts',
'Providence, Rhode Island',
'Manchester, New Hampshire',
'New York, New York',
'Springfield, Massachusets',
]
